### ISSUE TITLE
Support for All Drives & Network 

### ISSUE THREAD

**Issue by VIPKaiser** [whitewhidow/quest-sidenoder#44] opened 2020-12-27 18:13 UTC
Please add support for all hard drives on the local browse option including network drives mounted. 

Currently having to copy files to the users folder to install then delete and repeat.

**Comment by whitewhidow** [comment] 2020-12-27 18:16
will take care of it at some point, 

for now, as a temporary workaround, you could mount the other (network)drive as a folder on the primary drive, so that you could browse to it in sidenoder

**Comment by VIPKaiser** [comment] 2020-12-27 18:17
i'll do that now, thanks.

**Comment by VIPKaiser** [comment] 2020-12-27 18:25
That works fine, however after installing it then throws you back to the default directory...so you have to click to the correct folder again to do the next install. Can you please make it remember the last folder so it's a nicer experience.

**Comment by whitewhidow** [comment] 2020-12-28 13:10
> Can you please make it remember the last folder so it's a nicer experience.

this should now also be fixed on dev branch

**Comment by whitewhidow** [comment] 2020-12-28 23:00
ps easier temp workaround to get to another drive,   on the browse page,   in debug console,  run:

`ipcRenderer.send('get_dir', 'G:/');`   should browse to your G drive for example (plus after sideloading it will no longer switch back to other location)

**Comment by VIPKaiser** [comment] 2020-12-28 23:13
Excellent thanks!

**Comment by VIPKaiser** [comment] 2020-12-28 23:45
I usually use it on my Macbook as it seems quicker than the windows version. I've tested it on my windows rig and it crash with the following however:

browse.js:113 HOVER
index.twig:99 ask_sideload msg came ! 
index.twig:100 {"success":true, "path": "G:\VRP Sync\Downloads\Axegend v3.0.5 -unknown\Axegend [3.0.5].apk"}
VM152:1 Uncaught SyntaxError: Unexpected token V in JSON at position 29
    at JSON.parse (<anonymous>)
    at EventEmitter.<anonymous> (index.twig:101)
    at EventEmitter.emit (events.js:310)
    at Object.onMessage (electron/js2c/renderer_init.js:91)
(anonymous) @ index.twig:101
emit @ events.js:310
onMessage @ electron/js2c/renderer_init.js:91
browse.js:113 HOVER

**Comment by whitewhidow** [comment] 2020-12-29 00:08
did this occur after you did the `ipcRenderer.send('get_dir', 'G:/');`, and then navigated to another folder and then to the apk by clicking on it ?
OR
Did you navigate directly to that apk using `ipcRenderer.send('get_dir', 'G:\VRP Sync\Downloads\Axegend v3.0.5 -unknown\Axegend [3.0.5].apk');` ?

it seems the issue is the backslashes that should be forward slashes, i just need to know if it did indeed render the html on that page incorrectly, causing it to have wrong slashes,   or did you put them in ?

**ALSO**, do/did you ever get the same issue when navigating (mounted)folders otherwise, without using this `ipcRenderer` approach to get there?

thx

**Comment by VIPKaiser** [comment] 2020-12-29 08:58
Sorry this was a drag and drop test from my G drive. The backslashes will be the windows file path i.e. c:\windows\.

Scenario 1:

Loaded test version binary. 
Nothing changed in console.
Dragged an apk file from my G drive into main part
It just gets stuck at.... "Trying to fetch device storage info" and throws the same error in the console as above.
I have tried dragging to the main screen green part and the grey browse window both have the same outcome.

Scenario 2:

Loaded test version binary. 
Changed manually in console to G drive as specified.
Manually browsed to APK location.
Selected the same APK as i dragged.
This worked as expected!

Thanks.

**Comment by whitewhidow** [comment] 2020-12-29 11:07
drag and drop  request is in another issue ...   gonna get a bit too confusing this way ./... 

So the current issue is only with dropped files correct ?   using `ipcRenderer.send('get_dir', 'G:/');` to access g drive does work   right ?

**Comment by VIPKaiser** [comment] 2020-12-29 11:14
yeah sorry it was late i replied to the wrong thread. **Yes the only issue is with dropped files.**

ipcRenderer.send('get_dir', 'G:/'); to access g drive does work <-- correct

**Closed** 2022-05-25 20:43 UTC
Labels: enhancement
