### ISSUE TITLE
MacOS Mojave: "ADB global installation not found"

### ISSUE THREAD

**Issue by alex1115alex** [whitewhidow/quest-sidenoder#18] opened 2020-12-04 02:22 UTC
After installing the dependencies and running the .app from my Applications folder, SideNoder gives me an error saying saying "ADB global installation not found".

I installed the .app from the .dmg supplied on the latest release page.

Additionally, I definitely have ADB installed as I've used ADB countless times before on this installation (SideQuest, OSU, Google's Flutter framework + Android Studio Emulator), and reinstalling the android-platform-tools via brew doesn't help either.

**Comment by whitewhidow** [comment] 2020-12-04 02:39
SideQuest and OSU come with their own adb exectuable, so that would not meananything (they dont add it to PATH, so it does not become globally available)

But reinstalling the android-platform-tools via brew *should* have done this (confirm by just running the adb command in any random directory)

Can you confirm wether compiling and running the app manually, fixes the issue or not (as i suspect this is related to the packaged osx build, and that the issue is not present when manually built and run on osx, and that your adb is indeed correctly installed).

thx in advance.

**Comment by alex1115alex** [comment] 2020-12-04 02:45
Running adb from any directory works just fine as always.

I've just compiled it from source as you've suggested, and it works perfectly. You were right - the prepackaged MacOS build was just messed up.

**Comment by whitewhidow** [comment] 2020-12-04 13:01
going to leave this open, since i still need to fix it somehow (dont know why it is broken in the prebuilt versions atm)

**Comment by whitewhidow** [comment] 2020-12-04 19:41
Fixed in the current dev branch and release v0.0.4-alpha-DEV2

https://github.com/whitewhidow/quest-sidenoder/releases/tag/v0.0.4-alpha-DEV2

**Closed by whitewhidow** 2020-12-04 19:41 UTC
Labels: bug, help wanted
